classDiagram
direction TB
    class AntiPlagiarismSession {
        <<interface>>
        +invoke()
    }
    AntiPlagiarismSession *--> RunConfiguration

    class RunConfigurator {
        <<interface>>
    }
    CLIConfigurator ..|> RunConfigurator

    class RunConfiguration {
        <<inteface>>
    }
    RunConfigurator ..> RunConfiguration: << creates >>

    class RepositoryProvider {
        <<interface>>
    }
    class Repository {
        <<interface>>
    }
    Repository "2..*" <--* RunConfiguration
    RepositoryProvider ..> Repository: << creates >>

    class PlagiarismDetector {
        <<interface>>
    }
    RunConfiguration *--> "1" PlagiarismDetector

    class Analyzer {
        <<interface>>
    }
    RunConfiguration *--> "1" Analyzer

    class Filter {
        <<interface>>
    }
    RunConfiguration *--> "1" Filter

    class KnoledgeBaseRepository {
        <<interface>>
        + save()
        + load()
    }
    KnoledgeBaseRepository "1" <--* AntiPlagiarismSession

    class Output {
        <<interface>>
    }
    class ReportsExporter {
        <<interface>>
        +export(reports: Set~Report~)
    }
    Output <|-- ReportsExporter
    ReportsExporter <|.. FileExporter
    RunConfiguration *--> "1" ReportsExporter
    Output <|.. CLIOutput
    AntiPlagiarismSession *--> "1" Output