classDiagram
direction BT
    class PlagiarismDetector~in S: SourceRepresentation<T>, T, out M: Match~ {
        <<interface>>
        +invoke(first: S, second: S) ComparisonResult~M~
    }

    class ComparisonResult~out M: Match~ {
        <<interface>>
        +similarity: Double
        +matches: Sequence~M~
    }
    PlagiarismDetector -- ComparisonResult
    ComparisonResult <|.. TokenBasedComparisonResult~TokenMatch~

    class TokenBasedPlagiarismDetector~TokenizedSource, Sequence<Token, TokenMatch~ {
        -comparisonStrategy: ComparisonStrategy~TokenizedSource, Sequence<Token, TokenMatch~
        -similarityEstimationStrategy: TokenBasedSimilarityStrategy
        +invoke(Pair~TokenizedSource, TokenizedSource~) ComparisonResult~TokenMatch~
    }
    TokenBasedPlagiarismDetector ..|> PlagiarismDetector

    class SimilarityEstimationStrategy~in S: SourceRepresentation<T>, T, out M: Match~ {
        <<interface>>
        +similarityOf(representation: Pair~S, S~, matches: Set~M~) Double
    }
    class TokenBasedSimilarityStrategy~TokenizedSource, Sequence<Token>, TokenMatch~
    SimilarityEstimationStrategy <|-- TokenBasedSimilarityStrategy
    %% NormalizedAverageSimilarityStrategy ..|> TokenBasedSimilarityStrategy
    %% NormalizedMaxSimilarityStrategy ..|> TokenBasedSimilarityStrategy
    TokenBasedSimilarityStrategy --* TokenBasedPlagiarismDetector

    class ComparisonStrategy~in S: SourceRepresentation<T>, T, out M: Match~ {
        <<interface>>
        +invoke(representations: Pair~S, S~) Set~Match~
    }
    TokenBasedPlagiarismDetector *--> ComparisonStrategy

    BaseGreedyStringTiling~TokenizedSource, Sequence<Token>, TokenMatch~ ..|> ComparisonStrategy
    GreedyStringTiling --|> BaseGreedyStringTiling
    RKRGreedyStringTiling --|> BaseGreedyStringTiling

    class Match {
        <<interface>>
    }
    
    class TokenMatch {
        <<interface>>
        +pattern: Pair~TokenizedSource, List<Token>~
        +text: Pair~TokenizedSource, List<Token>~
        +length: Int
    }
    TokenMatch --|> Match
    ComparisonStrategy -- TokenMatch