classDiagram 
direction TB
    class Report {
        <<interface>>
        + scoreOfSimilarity: Double
    } 
    Report *-- "*" ComparisonResult

    class Repository {
        <<interface>>
        +name: String
        +owner: String
    }
    Report *-- "1" Repository: submittedProject
    Report *-- "1" Repository: comparedProject

    class AntiPlagiarismSession {
        <<interface>>
        +invoke()
    }
    AntiPlagiarismSession "1" -- "*" Report: generates
    AntiPlagiarismSession *-- "1" RunConfiguration

    class RunConfiguration {
        <<interface>>
    }
    RunConfiguration *-- "1" PlagiarismDetector
    RunConfiguration *-- "1" Analyzer
    RunConfiguration *-- "1" Filter
    Repository "*" --* RunConfiguration

    class PlagiarismDetector {
        <<interface>>
    }
    PlagiarismDetector "*" -- "2" SourceRepresentation: input

    class ComparisonResult {
        <<interface>>
    }
    ComparisonResult *-- "2" SourceRepresentation: refers to
    ComparisonResult "*" -- "1" PlagiarismDetector: output

    class Analyzer {
        <<interface>>
    }
    Analyzer "1" -- "1" SourceRepresentation: creates

    class Filter {
        <<interface>>
    }
    Filter "*" -- "*" SourceRepresentation: filters

    class SourceRepresentation {
        <<interface>>
    }

    class SourceFile {
        <<interface>>
        +fileName: String
    }
    Repository *-- "*" SourceFile
    SourceFile "1" -- "1" SourceRepresentation: of