classDiagram
direction BT
    class Repository {
        <<interface>>
        +name: String
        +owner: String
        +cloneUrl: URL
        +getSources(pattern: Regex) Sequence~File~
    }
    class AbstractRepository {
        <<abstract>>
        +getSources(pattern: Regex) Sequence~File~
    }
    AbstractRepository ..|> Repository
    class GitHubRepository {
        -repository: Repo
        +GitHubRepository(\nㅤㅤrepository: GHRepository\n)
    }
    class BitBucketRepository {
        -repoInfos: JSONObject
        +BitBucketRepository(\nㅤㅤrepoInfos: JSONObject\n)
    }
    GitHubRepository --|> AbstractRepository
    BitBucketRepository --|> AbstractRepository

    class RepoContentSupplierStrategy {
        <<interface>>
        +getFilesOf(\nㅤㅤextensions: Iterable~String~\n)
    }
    RepoContentSupplierStrategy <--* AbstractRepository
    CloneStrategy ..|> RepoContentSupplierStrategy