sequenceDiagram
    autonumber
    activate Main

    Main ->> CLIConfigurator: <<create>> <br/> sessionFrom(args)
    activate CLIConfigurator
    CLIConfigurator ->> CLIConfigurator: <<create>> <br/> configuration
    CLIConfigurator ->> AntiPlagiarismSession: <<create>> <br/> configure(configuration)
    CLIConfigurator -->> Main: session
    deactivate CLIConfigurator

    Main ->> AntiPlagiarismSession: run
    activate AntiPlagiarismSession

    loop for each submitted project
        loop for each corpus project
            note right of AntiPlagiarismSession: This nested loop is <br/> computed concurrently.
            AntiPlagiarismSession -) TokenizationFacade: execute()
            activate TokenizationFacade
            TokenizationFacade ->> TokenizationFacade: analyze()
            TokenizationFacade ->> TokenizationFacade: compare()
            TokenizationFacade -->> AntiPlagiarismSession: reports
            deactivate TokenizationFacade
        end

        AntiPlagiarismSession ->> CLIExporter: export(reports)
        activate CLIExporter
        CLIExporter ->> CLIExporter: data export
        CLIExporter -->> AntiPlagiarismSession: 
        deactivate CLIExporter
    end

    AntiPlagiarismSession -->> Main: 
    deactivate AntiPlagiarismSession

    deactivate Main